apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: node-crd-lifecycle
    name: node-crd-lifecycle-exp
    namespace: saas-customers
  spec:
    ports:
    - port: 3001
      targetPort: 3001
    selector:
      name: node-crd-lifecycle
    type: LoadBalancer
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: node-crd-lifecycle
    name: node-crd-lifecycle
    namespace: saas-customers
    resourceVersion: "55059611"
    selfLink: /api/v1/namespaces/saas-customers/replicationcontrollers/node-crd-lifecycle
    uid: de3310c1-69b7-11e8-ad39-42010a80007a
  spec:
    replicas: 1
    selector:
      name: node-crd-lifecycle
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: node-crd-lifecycle
      spec:
        containers:
        - env:
          - name: TOKEN
###            value: <REPLACE_THIS> ###
          image: gcr.io/gke-verification/github-blackducksoftware-node-crd-lifecycle:master
          imagePullPolicy: Always
          name: nrd-crd-lifecycle
          ports:
          - containerPort: 3001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
