apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: node-crd-lifecycle
    name: node-crd-lifecycle-exp
  spec:
    ports:
    - port: 3001
      targetPort: 3001
    selector:
      name: node-crd-lifecycle
    type: LoadBalancer
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: node-crd-lifecycle
    name: node-crd-lifecycle
    resourceVersion: "55059611"
    selfLink: /api/v1/namespaces/saas-customers/replicationcontrollers/node-crd-lifecycle
    uid: de3310c1-69b7-11e8-ad39-42010a80007a
  spec:
    replicas: 1
    selector:
      name: node-crd-lifecycle
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: node-crd-lifecycle
      spec:
        volumes:
        - name: google-cloud-key
          secret:
            secretName: gcloud-key
        containers:
        - env:
          - name: TOKEN
###            value: <REPLACE_THIS> ###
          image: gcr.io/gke-verification/github-blackducksoftware-node-crd-lifecycle:master
          imagePullPolicy: Always
          name: nrd-crd-lifecycle
          ports:
          - containerPort: 3001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/var/secrets/google/key.json"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
